version: '3.7'
services:
  app-network:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${NODE_PORT}"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
